#include <unistd.h>

#include "../libs/rtklib-2.4.3/src/rtklib.h"

#include "../include/simulator.h"

void dumpEphemeride(eph_t* ephemerides, int index) {
    FILE* dump_file = fopen("gnss-sim-ephemeris.txt", "a+");
    
    // NOTE: SVs transmit some values in "semicircles". Our supplied RINEX file presents these values
    //       in radians (part of the RINEX spec). These are converted to semicircles later. They are
    //       displayed in radians here so that they can be compared with the "gps_ephemeris.xml"
    //       generated by GNSS-SDR for debugging.
    fprintf(dump_file, "\nPRN: %i\n", ephemerides[index].sat);
    fprintf(dump_file, "M_0: %.17e\n", ephemerides[index].M0);
    fprintf(dump_file, "delta_n: %.17e\n", ephemerides[index].deln);
    fprintf(dump_file, "ecc: %.17e\n", ephemerides[index].e);
    fprintf(dump_file, "sqrtA: %.17e\n", sqrt(ephemerides[index].A));
    fprintf(dump_file, "OMEGA_0: %.17e\n", ephemerides[index].OMG0);
    fprintf(dump_file, "i_0: %.17e\n", ephemerides[index].i0);
    fprintf(dump_file, "omega: %.17e\n", ephemerides[index].omg);
    fprintf(dump_file, "OMEGAdot: %.17e\n", ephemerides[index].OMGd);
    fprintf(dump_file, "idot: %.17e\n", ephemerides[index].idot);
    fprintf(dump_file, "Cuc: %.17e\n", ephemerides[index].cuc);
    fprintf(dump_file, "Cus: %.17e\n", ephemerides[index].cus);
    fprintf(dump_file, "Crc: %.17e\n", ephemerides[index].crc);
    fprintf(dump_file, "Crs: %.17e\n", ephemerides[index].crs);
    fprintf(dump_file, "Cic: %.17e\n", ephemerides[index].cic);
    fprintf(dump_file, "Cis: %.17e\n", ephemerides[index].cis);
    fprintf(dump_file, "toe: %i\n", (unsigned long)time2gpst(ephemerides[index].toe, NULL));
    fprintf(dump_file, "toc: %i\n", (unsigned long)time2gpst(ephemerides[index].toc, NULL));
    fprintf(dump_file, "af0: %.17e\n", ephemerides[index].f0);
    fprintf(dump_file, "af1: %.17e\n", ephemerides[index].f1);
    fprintf(dump_file, "af2: %.17e\n", ephemerides[index].f2);

    // The value transmitted is the modulo 1024 of the actual week number.
    // Need to perform this modulo (using bitmask) if we want to compare values.
    fprintf(dump_file, "WN: %i\n", (ephemerides[index].week & BITMASK(10)));

    fprintf(dump_file, "SV_accuracy: %i\n", ephemerides[index].sva);
    fprintf(dump_file, "SV_health: %i\n", ephemerides[index].svh);
    fprintf(dump_file, "TGD: %.17e\n", ephemerides[index].tgd[0]);
    fprintf(dump_file, "IODC: %i\n", ephemerides[index].iodc);

    fclose(dump_file);
}

void printNavmessage(unsigned long frame[SUBFRAME_COUNT][WORD_COUNT]) {
    for (short subframe = 0; subframe < SUBFRAME_COUNT; subframe++) {
        printf("SUBFRAME %i: \n", (subframe + 1));
        for (short word = 0; word < WORD_COUNT; word++) {
            printf("%i\t%030b\n", (word + 1), frame[subframe][word]);
        }

        printf("\n");
    }
}

void dumpChannels(gtime_t newSimulationTime, Channel* channels, int channelCount) {
    static gtime_t previousSimulationTime;
    static double simulationTime;

    // If this is the first call (static variables should be initilized to 0)...
    if (previousSimulationTime.time == 0) {
        previousSimulationTime = newSimulationTime;
    }

    else {
        // Update the simulation time record
        simulationTime = simulationTime + timediff(newSimulationTime, previousSimulationTime);
        previousSimulationTime = newSimulationTime;
    }

    // Open file in append mode
    FILE* dump_file = fopen("channel-dump.txt", "a+");

    // Move the file pointer to the end
    fseek(dump_file, 0, SEEK_END);

    // Get the current position, which indicates the file size
    long size = ftell(dump_file);

    // Add the header if the file does not already exist
    if (size == 0) {
        fprintf(dump_file,
            "Time [s]\t\
            PRN\t\
            Pseudorange [m]\t\
            Pseudorange Rate [ms]\t\
            SV Position X [m]\t\
            SV Position Y [m]\t\
            SV Position Z [m]\t\
            Elevation [rad]\t\
            Carrier Doppler [Hz]\t\
            Code Doppler [Hz]\t\
            Code Frequency [Hz]\t\
            Code Chip Pointer\t\
            Nav Bit Pointer\t\
            Carrier Phase [cycles]\n"           
        );
    }

    // Dump the data!
    for (int i = 0; i < channelCount; i++) {
        fprintf(dump_file,
            "%.3f\t\
            %i\t\
            %.2f\t\
            %.2f\t\
            %.2f\t\
            %.2f\t\
            %.2f\t\
            %.2f\t\
            %.2f\t\
            %.2f\t\
            %.2f\t\
            %.2f\t\
            %i\t\
            %.2f\n",

            simulationTime,
            channels[i].sv->prn,
            channels[i].sv->psuedorange_m,
            channels[i].sv->psuedorangeRate_ms,
            channels[i].sv->position_ecef[0],
            channels[i].sv->position_ecef[1],
            channels[i].sv->position_ecef[2],
            channels[i].sv->elevation_rad,
            channels[i].carrierDopplerShift_Hz,
            channels[i].codeDopplerShift_Hz,
            channels[i].codeFrequency_Hz,
            channels[i].codeChipPointer,
            channels[i].navBitPointer,
            channels[i].carrierPhase_cycles
        );
    }

    // Close the file
    fclose(dump_file);
}